### ISSUE TITLE
Fix rule parameters

### ISSUE THREAD

**Issue by agstrauss** [morphlang/tree-sitter-morph#38]
This fails:
```
morph Foo mutates Bar {
  foo -> (self) => self<foo>['foo']
}
```
The <foo> is probably causing issues.

**Comment by garciafido** [comment]
The actual syntax is:

morph Foo mutates Bar {
  foo -> **lambda** (self) => self<foo>['foo']
}

**Comment by agstrauss** [comment]
You're right Dr. Fidious, but there's nonetheless an error:
This:
```
self<foo>['foo']
```
Is interpreted as a lessThan, greaterThan expression

**Comment by agstrauss** [comment]
Remove rule parameters for now
